update Dockerfile.train

diff --git a/STT/Dockerfile.train b/STT/Dockerfile.train
--- a/STT/Dockerfile.train
+++ b/STT/Dockerfile.train
@@ -1,12 +1,210 @@
-FROM nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04
+# >> START Build STT
 
-ARG ds_repo=mozilla/DeepSpeech
-ARG ds_branch=4270e22fe02f4fa7430a721ac917f6353c36f455
-ARG ds_sha1=4270e22fe02f4fa7430a721ac917f6353c36f455
-ARG cc_repo=mozilla/CorporaCreator
-ARG cc_sha1=73622cf8399f8e634aee2f0e76dacc879226e3ac
+# Need devel version cause we need /usr/include/cudnn.h
+FROM nvidia/cuda:10.1-cudnn7-devel-ubuntu18.04 as stt-build
+
+ARG stt_repo=wasertech/STT
+#coqui-ai/STT
+ARG stt_branch=aee6956a9bee8bda89dba35378a39e6fe2963c62
+#8aa2b13e987e2f397b6b6b3ca1ae81c7ebac72d1
+ARG stt_sha1=aee6956a9bee8bda89dba35378a39e6fe2963c62
+#8aa2b13e987e2f397b6b6b3ca1ae81c7ebac72d1
+
+# Get basic packages
+RUN apt-get update && apt-get install -y --no-install-recommends \
+        apt-utils \
+        bash-completion \
+        build-essential \
+        ca-certificates \
+        cmake \
+        curl \
+        g++ \
+        gcc \
+        git \
+        libbz2-dev \
+        libboost-all-dev \
+        libgsm1-dev \
+        libltdl-dev \
+        liblzma-dev \
+        libmagic-dev \
+        libpng-dev \
+        libsox-fmt-mp3 \
+        libsox-dev \
+        locales \
+        openjdk-8-jdk \
+        pkg-config \
+        python3 \
+        python3-dev \
+        python3-pip \
+        python3-wheel \
+        python3-numpy \
+        sox \
+        unzip \
+        wget \
+        zlib1g-dev
+
+RUN update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
+RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
+
+# Install Bazel
+RUN curl -LO "https://github.com/bazelbuild/bazel/releases/download/3.1.0/bazel_3.1.0-linux-x86_64.deb"
+RUN dpkg -i bazel_*.deb
+
+# Try and free some space
+RUN rm -rf /var/lib/apt/lists/*
+
+# << END Install base software
+
+# >> START Configure Tensorflow Build
+
+# GPU Environment Setup
+ENV TF_NEED_ROCM 0
+ENV TF_NEED_OPENCL_SYCL 0
+ENV TF_NEED_OPENCL 0
+ENV TF_NEED_CUDA 1
+ENV TF_CUDA_PATHS "/usr,/usr/local/cuda-10.1,/usr/lib/x86_64-linux-gnu/"
+ENV TF_CUDA_VERSION 10.1
+ENV TF_CUDNN_VERSION 7.6
+ENV TF_CUDA_COMPUTE_CAPABILITIES 6.0
+ENV TF_NCCL_VERSION 2.8
+
+# Common Environment Setup
+ENV TF_BUILD_CONTAINER_TYPE GPU
+ENV TF_BUILD_OPTIONS OPT
+ENV TF_BUILD_DISABLE_GCP 1
+ENV TF_BUILD_ENABLE_XLA 0
+ENV TF_BUILD_PYTHON_VERSION PYTHON3
+ENV TF_BUILD_IS_OPT OPT
+ENV TF_BUILD_IS_PIP PIP
+
+# Other Parameters
+ENV CC_OPT_FLAGS -mavx -mavx2 -msse4.1 -msse4.2 -mfma
+ENV TF_NEED_GCP 0
+ENV TF_NEED_HDFS 0
+ENV TF_NEED_JEMALLOC 1
+ENV TF_NEED_OPENCL 0
+ENV TF_CUDA_CLANG 0
+ENV TF_NEED_MKL 0
+ENV TF_ENABLE_XLA 0
+ENV TF_NEED_AWS 0
+ENV TF_NEED_KAFKA 0
+ENV TF_NEED_NGRAPH 0
+ENV TF_DOWNLOAD_CLANG 0
+ENV TF_NEED_TENSORRT 0
+ENV TF_NEED_GDR 0
+ENV TF_NEED_VERBS 0
+ENV TF_NEED_OPENCL_SYCL 0
+
+ENV PYTHON_BIN_PATH /usr/bin/python3.6
+ENV PYTHON_LIB_PATH /usr/local/lib/python3.6/dist-packages
+
+# << END Configure Tensorflow Build
+
+# >> START Configure Bazel
+
+# Running bazel inside a `docker build` command causes trouble, cf:
+#   https://github.com/bazelbuild/bazel/issues/134
+# The easiest solution is to set up a bazelrc file forcing --batch.
+RUN echo "startup --batch" >>/etc/bazel.bazelrc
+# Similarly, we need to workaround sandboxing issues:
+#   https://github.com/bazelbuild/bazel/issues/418
+RUN echo "build --spawn_strategy=standalone --genrule_strategy=standalone" \
+    >>/etc/bazel.bazelrc
+
+# << END Configure Bazel
+
+WORKDIR /
+RUN git clone https://github.com/${stt_repo} STT && cd /STT && git checkout ${stt_branch} && git submodule sync && git submodule update --init tensorflow
+
+# >> START Build and bind
+
+WORKDIR /STT/tensorflow
+
+# Fix for not found script https://github.com/tensorflow/tensorflow/issues/471
+RUN /STT/tensorflow/configure
+
+# Using CPU optimizations:
+# -mtune=generic -march=x86-64 -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx.
+# Adding --config=cuda flag to build using CUDA.
+
+# passing LD_LIBRARY_PATH is required cause Bazel doesn't pickup it from environment
+
+# Build STT
+RUN bazel build \
+	--verbose_failures \
+	--workspace_status_command="bash native_client/bazel_workspace_status_cmd.sh" \
+    --config=cuda \
+    -c opt \
+	--copt=-mtune=generic \
+	--copt=-march=x86-64 \
+	--copt=-msse \
+	--copt=-msse2 \
+	--copt=-msse3 \
+	--copt=-msse4.1 \
+	--copt=-msse4.2 \
+	--copt=-mavx \
+	--config=noaws \
+	--config=nogcp \
+	--config=nohdfs \
+	--config=nonccl \
+    //native_client:libstt.so
+
+# Copy built libs to /STT/native_client
+RUN cp bazel-bin/native_client/libstt.so /STT/native_client/
+
+# Build client.cc and install Python client and decoder bindings
+ENV TFDIR /STT/tensorflow
+
+RUN nproc
+
+WORKDIR /STT/native_client
+RUN make NUM_PROCESSES=$(nproc) stt
+
+WORKDIR /STT
+RUN cd native_client/python && make NUM_PROCESSES=$(nproc) bindings
+
+
+# << END Build and bind
+
+
+# Build KenLM
+FROM nvcr.io/nvidia/tensorflow:20.06-tf1-py3 AS kenlm-build
+
 ARG kenlm_repo=kpu/kenlm
 ARG kenlm_branch=87e85e66c99ceff1fab2500a7c60c01da7315eec
+ENV DEBIAN_FRONTEND=noninteractive
+
+RUN apt-get update && \
+    apt-get install -y --no-install-recommends \
+    build-essential cmake libboost-system-dev \
+    libboost-thread-dev libboost-program-options-dev \
+    libboost-test-dev libeigen3-dev zlib1g-dev \
+    libbz2-dev liblzma-dev && \
+    rm -rf /var/lib/apt/lists/*
+
+# Build KenLM to generate new scorers
+WORKDIR /code
+
+RUN git clone https://github.com/${kenlm_repo} && \
+    cd /code/kenlm && \
+	git checkout $kenlm_branch && \
+    mkdir -p build && \
+    cd build && \
+    cmake .. && \
+    make -j $(nproc) || \
+    ( echo "ERROR: Failed to build KenLM."; \
+    echo "ERROR: Make sure you update the kenlm submodule on host before building this Dockerfile."; \
+    echo "ERROR: $ cd STT; git submodule update --init kenlm"; \
+    exit 1; )
+
+
+# Final image for training
+FROM nvidia/cuda:10.0-cudnn7-runtime-ubuntu18.04
+#nvcr.io/nvidia/tensorflow:20.06-tf1-py3
+
+# Import Args in Env
+ARG cc_repo=mozilla/CorporaCreator
+ARG cc_sha1=73622cf8399f8e634aee2f0e76dacc879226e3ac
 
 # Model parameters
 ARG model_language=fr
@@ -19,7 +217,7 @@ ENV BATCH_SIZE=$batch_size
 ARG n_hidden=2048
 ENV N_HIDDEN=$n_hidden
 
-ARG epochs=30
+ARG epochs=35
 ENV EPOCHS=$epochs
 
 ARG learning_rate=0.0001
@@ -72,46 +270,65 @@ ENV DEBIAN_FRONTEND noninteractive
 
 ENV HOMEDIR /home/trainer
 
-ENV VIRTUAL_ENV_NAME ds-train
+ENV VIRTUAL_ENV_NAME stt-train
 ENV VIRTUAL_ENV $HOMEDIR/$VIRTUAL_ENV_NAME
-ENV DS_DIR $HOMEDIR/ds
+ENV STT_DIR $HOMEDIR/stt
+ENV KENLM_BIN $STT_DIR/kenlm/build/bin
 ENV CC_DIR $HOMEDIR/cc
 
-ENV DS_BRANCH=$ds_branch
-ENV DS_SHA1=$ds_sha1
+ENV PATH="$KENLM_BIN:${HOMEDIR}/.local/bin:${VIRTUAL_ENV}/bin:$PATH"
 
-ENV PATH="$VIRTUAL_ENV/bin:$PATH"
+ENV LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$STT_DIR:$KENLM_BIN:${STT_DIR}/data/lm"
 
 RUN env
 
-# Get basic packages
-RUN apt-get -qq update && apt-get -qq install -y --no-install-recommends \
-    build-essential \
-    curl \
-    wget \
-    git \
-    ffmpeg \
-    python3 \
-    python3-pip \
-    ca-certificates \
-    cmake \
-    libboost-all-dev \
-    zlib1g-dev \
-    libbz2-dev \
-    liblzma-dev \
-    pkg-config \
-    g++ \
-    virtualenv \
-    unzip \
-    pixz \
-    sox \
-    sudo \
-    libsox-fmt-all \
-    locales locales-all \
-    xz-utils
+# We need to purge python3-xdg because
+# it's breaking STT install later with
+# errors about setuptools
+#
+RUN apt-get -qq update && \
+    apt-get -qq install -y --no-install-recommends \
+        build-essential \
+        curl \
+        wget \
+        git \
+        ffmpeg \
+        python3 \
+        python3-pip \
+        ca-certificates \
+        cmake \
+        libboost-all-dev \
+        zlib1g-dev \
+        libbz2-dev \
+        liblzma-dev \
+        libmagic-dev \
+        libopus0 \
+        libopusfile0 \
+        libsndfile1 \
+        pkg-config \
+        g++ \
+        virtualenv \
+        unzip \
+        pixz \
+        sox \
+        sudo \
+        libsox-fmt-all \
+        locales locales-all \
+        xz-utils && \
+    apt-get purge -y python3-xdg && \
+    rm -rf /var/lib/apt/lists/*
 
+RUN update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
+RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1
+
+# Make sure pip and its dependencies are up-to-date
+RUN pip3 install --upgrade pip wheel setuptools
+
+# Creating user for security purposes
 RUN groupadd -g $GID trainer && \
     adduser --system --uid $UID --group trainer
+
+#RUN mkdir -p /etc/sudoers.d
 
 RUN echo "trainer ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/trainer && \
     chmod 0440 /etc/sudoers.d/trainer
@@ -121,41 +338,36 @@ USER trainer
 
 WORKDIR $HOMEDIR
 
-RUN wget -O - https://gitlab.com/libeigen/eigen/-/archive/3.2.8/eigen-3.2.8.tar.bz2 | tar xj
-
-RUN git clone https://github.com/$kenlm_repo.git && cd kenlm && git checkout $kenlm_branch \
-    && mkdir -p build \
-    && cd build \
-    && EIGEN3_ROOT=$HOMEDIR/eigen-eigen-07105f7124f9 cmake .. \
-    && make -j
-
-WORKDIR $HOMEDIR
-
 RUN virtualenv --python=/usr/bin/python3 $VIRTUAL_ENV_NAME
 
-ENV PATH=$HOMEDIR/$VIRTUAL_ENV_NAME/bin:$PATH
+# Copy files from previous build stages
+COPY --chown=trainer:trainer --from=stt-build /STT ${STT_DIR}
 
-RUN git clone https://github.com/$ds_repo.git $DS_DIR
+WORKDIR $STT_DIR
+# Build CTC decoder first, to avoid clashes on incompatible versions upgrades
+RUN cd native_client/ctcdecode && make NUM_PROCESSES=$(nproc) bindings
+RUN ${VIRTUAL_ENV}/bin/python -m pip install --upgrade native_client/ctcdecode/dist/*.whl
 
-WORKDIR $DS_DIR
+RUN mkdir -p ${STT_DIR}/kenlm/build/
+COPY --chown=trainer:trainer --from=kenlm-build /code/kenlm/build/bin ${STT_DIR}/kenlm/build/bin
 
-RUN git checkout $ds_branch
+# Tool to convert output graph for inference
+RUN curl -L https://github.com/coqui-ai/STT/releases/download/v0.9.3/convert_graphdef_memmapped_format.linux.amd64.zip | funzip > convert_graphdef_memmapped_format && \
+    chmod +x convert_graphdef_memmapped_format
 
-WORKDIR $DS_DIR
+# Pre-built native client tools
+RUN curl -L https://github.com/coqui-ai/STT/releases/download/v1.1.0/native_client.tflite.Linux.tar.xz | tar -xJvf - && rm ${STT_DIR}/libsox.so.*
 
-RUN pip install --upgrade pip==20.0.2 wheel==0.34.2 setuptools==46.1.3
-RUN DS_NOTENSORFLOW=y pip install --upgrade --force-reinstall -e .
-RUN pip install --upgrade tensorflow-gpu==1.15.4
+# Install STT
+# No need for the decoder since we did it earlier
 
-RUN TASKCLUSTER_SCHEME="https://community-tc.services.mozilla.com/api/index/v1/task/project.deepspeech.tensorflow.pip.%(branch_name)s.%(arch_string)s/artifacts/public/%(artifact_name)s" python util/taskcluster.py \
-	--target="$(pwd)" \
-	--artifact="convert_graphdef_memmapped_format" \
-	--branch="r1.15" && chmod +x convert_graphdef_memmapped_format
+RUN ${VIRTUAL_ENV}/bin/python -m pip install --upgrade native_client/python/dist/*.whl
 
-RUN python util/taskcluster.py \
-	--target="$(pwd)" \
-	--artifact="native_client.tar.xz" && ls -hal generate_scorer_package 
+RUN DS_NODECODER=y DS_NOTENSORFLOW=y python -m pip install --upgrade -e .
 
+RUN ${VIRTUAL_ENV}/bin/python -m pip install --upgrade 'tensorflow-gpu==1.15.4'
+
+# Install Corpus creator
 WORKDIR $HOMEDIR
 
 RUN git clone https://github.com/$cc_repo.git $CC_DIR
@@ -172,22 +384,27 @@ COPY --chown=trainer:trainer corpora.patch $CC_DIR
 RUN patch -p1 < corpora.patch
 
 # error: parso 0.7.0 is installed but parso<0.9.0,>=0.8.0 is required by {'jedi'}
-RUN pip install parso==0.8.1
+RUN ${VIRTUAL_ENV}/bin/python -m pip install parso==0.8.3
 
-RUN pip install modin[all]
+RUN ${VIRTUAL_ENV}/bin/python -m pip install --upgrade pip~=21.3.1 wheel~=0.37.0 setuptools~=59.6.0
 
-RUN python setup.py install
+RUN ${VIRTUAL_ENV}/bin/python -m pip install modin[all]
+
+RUN ${VIRTUAL_ENV}/bin/python setup.py install
 
 # For CC PMF importer
-RUN pip install num2words
+RUN ${VIRTUAL_ENV}/bin/python -m pip install num2words zipfile38
 
-WORKDIR $HOMEDIR
+# For MLS importer
+RUN ${VIRTUAL_ENV}/bin/python -m pip install git+https://github.com/TeamPyOgg/PyOgg
 
-ENV PATH="$HOMEDIR/kenlm/build/bin/:$PATH"
+WORKDIR ${HOMEDIR}
 
 # Copy now so that docker build can leverage caches
-COPY --chown=trainer:trainer . $HOMEDIR/
+COPY --chown=trainer:trainer . ${HOMEDIR}/
 
-COPY --chown=trainer:trainer ${MODEL_LANGUAGE}/ $HOMEDIR/${MODEL_LANGUAGE}/
+COPY --chown=trainer:trainer ${MODEL_LANGUAGE}/ ${HOMEDIR}/${MODEL_LANGUAGE}/
+
+WORKDIR ${HOMEDIR}
 
 ENTRYPOINT "$HOMEDIR/run.sh"
